# Nom del lloc
site_name: PROYECTO INTERMODULAR

# Carpeta amb el documents font
docs_dir: 'md'

# Carpeta on es generarà el lloc web (mkdocs build)
site_dir: 'docs'

# Adreça on s'executa el server local (mkdocs serve)
dev_addr: localhost:4000

# Navegació dels documents
nav:
- Inicio: index.md
- Markdown:
  - Introducción: markdown/introduccion.md
  - Editores: markdown/editores.md
  - Sintaxis básica: markdown/sintaxis.md
  - Referencias: markdown/referencias.md
- MkDocs:
  - Introducción: mkdocs/introduccion.md
  - Instalación: mkdocs/instalacion.md
  - Configuración: mkdocs/configuracion.md
  - Alojamiento en GitHub: mkdocs/github.md
  - Referencias: mkdocs/referencias.md

# Extenions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Tema a triar
theme: 
  name: material   # selecció del tema - mkdocs o readthedocs / material (pip install mkdocs-material)
  highlightjs: true
  palette:
   # Boto que canvia a mode oscur
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Botó que canvia a mode clar
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # utilitats de copia de codi
    - content.code.copy 
    - content.code.select
    - content.code.annotate
    - navigation.top    # boto flotant de tornar a dalt 

extra_css:
  - css/extra.css

# Altres afegits
plugins:
  - search      # plugin del quadre cerca
